version: '3.8'

services:
  app:
    build:
      dockerfile: conf/docker/dev/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - APP_CONFIG_PATH=$APP_CONFIG_PATH
      - PRODUCTION=$PRODUCTION
      - LOG_LEVEL=$LOG_LEVEL
      - MIN_CONNS=$MIN_CONNS
      - MAX_CONNS=$MAX_CONNS
      - MAX_CONN_LIFE_TIME=$MAX_CONN_LIFE_TIME
      - MAX_CONNIDLE_TIME=$MAX_CONNIDLE_TIME
      - HEALTH_CHECK_PERIOD=$HEALTH_CHECK_PERIOD
      - EM_API=$EM_API
    volumes:
      - .:/usr/src/app
    command: air -c ./conf/.air.toml ./cmd/main.go -b 0.0.0.0
    depends_on:
      db:
        condition: service_healthy

  db:
    extends:
      file: conf/docker/docker-compose-base.yml
      service: db
    ports:
      - "5434:5432"


networks:
  default:
    name: em_test_task_dev